### ISSUE TITLE
user interface improvemnt 1

### ISSUE THREAD

**Issue by fuzeyu** [fuzeyu/2020-GPW-L5K1-E#10]
Discuss the trouble when you create the user interface, make some improvement of this interface with codes and css style.

**Comment by fuzeyu** [comment]
@buxxuan @Les1ieLee   Please do your work as soon as possible.

**Comment by buxxuan** [comment]
This week, we can modify the interface based on the template and make a login system according to the template found

**Comment by fuzeyu** [comment]
> This week, we can modify the interface based on the template and make a login system according to the template found

Yes, here we go!

**Comment by fuzeyu** [comment]
Importantly, make sure we can obey the basic requirements.

**Comment by buxxuan** [comment]
> Importantly, make sure we can obey the basic requirements.
Of course, that's the basis of the design of the system

**Comment by buxxuan** [comment]
We had to set a time for the work to be delivered, so that it was clear to us that the work should be done long before the deadline, with a sense of urgency.  You are the group leader, I think you can tell us the deadline about the assigned work.

**Comment by Les1ieLee** [comment]
> We had to set a time for the work to be delivered, so that it was clear to us that the work should be done long before the deadline, with a sense of urgency. You are the group leader, I think you can tell us the deadline about the assigned work.

For the front-end and back-end work arrangement, @buxxuan and I can be responsible for the front-end development of user interface design, and @fuzeyu @18996073359  are responsible for the database design of back-end and management interface.
