### ISSUE TITLE
Design and development of background system

### ISSUE THREAD

**Issue by fuzeyu** [fuzeyu/2020-GPW-L5K1-E#21]
The backstage system starts to develop, the first task is to design the database

**Comment by fuzeyu** [comment]
The background system mainly manages the information of employees, tickets and customers. Therefore, in order to build a good background system, we need to design our database.  In the previous sprint I uploaded an ERD for reference.

**Comment by 18996073359** [comment]
We need to redesign the database now, because considering the complexity of data, I think we can first create the most basic data tables, such as user tables, route tables and ticket tables.

**Comment by 18996073359** [comment]
Here I think we can use the soft connection of the database for association, so that the data operation is more flexible, and we can directly change what kind of data we need in the back-end PHP.

**Comment by fuzeyu** [comment]
Whether to join the form of system user, because the user needs to log in to the background system

**Comment by fuzeyu** [comment]
Yes i agree with you

**Comment by fuzeyu** [comment]
We can use phpMyAdmin to build some basic tables
