### ISSUE TITLE
Project backlog

### ISSUE THREAD

**Issue by fuzeyu** [fuzeyu/2020-GPW-L5K1-E#3]
Tomorrow we will prioritize the functions of the system. Everybody can list the function points of our system first, and then we will discuss the priority of the function together.

**Comment by fuzeyu** [comment]
[product backlog.xlsx](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4498682/product.backlog.xlsx)
This is a product backlog I made. If you have other ideas, you can add them directly. Or we can  discussion first and add it after our discussion. @buxxuan @Les1ieLee @18996073359

**Comment by fuzeyu** [comment]
![image](https://user-images.githubusercontent.com/44355645/79684216-383ab980-8262-11ea-8669-2eafbaa7f077.png)

**Comment by fuzeyu** [comment]
![image](https://user-images.githubusercontent.com/44355645/79684268-8485f980-8262-11ea-8b39-aa6832a8f0bf.png)

**Comment by buxxuan** [comment]
> [product backlog.xlsx](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4498682/product.backlog.xlsx)
> 这是我制作的产品积压。如果您还有其他想法，可以直接添加。或者我们可以先讨论，然后在讨论后添加。@buxxuan @ Les1ieLee @ 18996073359

I think the types of tickets can be increased in terms of user demand, for example, customers can choose one-way tickets or round-trip tickets. I haven't added this to the product backlog yet, just taken it out for discussion

**Comment by fuzeyu** [comment]
> > [product backlog.xlsx](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4498682/product.backlog.xlsx)
> > 这是我制作的产品积压。如果您还有其他想法，可以直接添加。或者我们可以先讨论，然后在讨论后添加。@buxxuan @ Les1ieLee @ 18996073359
> 
> I think the types of tickets can be increased in terms of user demand, for example, customers can choose one-way tickets or round-trip tickets. I haven't added this to the product backlog yet, just taken it out for discussion
That is good. I will add it

**Comment by fuzeyu** [comment]
> > [product backlog.xlsx](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4498682/product.backlog.xlsx)
> > 这是我制作的产品积压。如果您还有其他想法，可以直接添加。或者我们可以先讨论，然后在讨论后添加。@buxxuan @ Les1ieLee @ 18996073359
> 
> I think the types of tickets can be increased in terms of user demand, for example, customers can choose one-way tickets or round-trip tickets. I haven't added this to the product backlog yet, just taken it out for discussion

That is good. I will add it

**Comment by buxxuan** [comment]
Why list the passengers who spend the most on the bus, a requirement I don't quite understand.

**Comment by 18996073359** [comment]
> Why list the passengers who spend the most on the bus, a requirement I don't quite understand.

Because the appendix requires this requirement.

**Comment by fuzeyu** [comment]
> Why list the passengers who spend the most on the bus, a requirement I don't quite understand.


Because this is the assignment given by the teacher

**Comment by fuzeyu** [comment]
> Why list the passengers who spend the most on the bus, a requirement I don't quite understand.


Because this is the assignment given by the teacher

**Comment by fuzeyu** [comment]
> Why list the passengers who spend the most on the bus, a requirement I don't quite understand.

Because this is the requirement in the assignment sub page given by the teacher.

**Comment by fuzeyu** [comment]
This is the updated product backlog
[product backlog.xlsx](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4499141/product.backlog.xlsx)

**Comment by 18996073359** [comment]
> This is the updated product backlog
> [product backlog.xlsx](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4499141/product.backlog.xlsx)

I think the product backlog is basically perfect, which can meet the requirements of the assignment appendix given by the teacher one by one. Now we can carry out detailed design according to the priority plan, and then to realize the function. Then we can add some additional functions, such as the manager can add new management personnel, and the customer can have special functions such as membership card.

**Comment by Les1ieLee** [comment]
> > 这是更新的产品积压
> > [产品backlog.xlsx](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4499141/product.backlog.xlsx)
> 
> 我认为积压产品基本上是完美的，可以满足老师一一给出的作业附录的要求。现在我们可以根据优先级计划进行详细设计，然后实现功能。然后，我们可以添加一些其他功能，例如经理可以添加新的管理人员，而客户可以具有特殊功能，例如会员卡。



> > This is the updated product backlog
> > [product backlog.xlsx](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4499141/product.backlog.xlsx)
> 
> I think the product backlog is basically perfect, which can meet the requirements of the assignment appendix given by the teacher one by one. Now we can carry out detailed design according to the priority plan, and then to realize the function. Then we can add some additional functions, such as the manager can add new management personnel, and the customer can have special functions such as membership card.

Some valuable functional suggestions can be added to our project backlog after discussion. Let's talk about the time the team intends to spend on each function.

**Comment by Les1ieLee** [comment]
https://www.atlassian.com/agile/scrum/backlogs
This is the website I found may help us better complete the project backlog.
