### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by fuzeyu** [fuzeyu/2020-GPW-L5K1-E#4]
We can prepare to create a database, for instance drawing an ERD.

**Comment by fuzeyu** [comment]
This is my ERD. You can give me some suggestions so that I can modi
[Untitled Diagram.vpd.pdf](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4528720/Untitled.Diagram.vpd.pdf)
fy it

**Comment by fuzeyu** [comment]
![image](https://user-images.githubusercontent.com/44355645/80210778-e9788f80-8666-11ea-8bbc-f1476a2f5b61.png)

**Comment by buxxuan** [comment]
![SFFJP%T9VGO2J8Q~ UC5QVT](https://user-images.githubusercontent.com/45254027/80275472-fe5f2c80-8713-11ea-8bed-23a836e35fd7.png)

**Comment by buxxuan** [comment]
[ERD.pdf](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4532647/ERD.pdf)

**Comment by 18996073359** [comment]
Both partners are great and hard working, and in terms of both, personal preference one.

**Comment by fuzeyu** [comment]
Make sure how many tables of management interface and sales interface we need to create in PMA. Everyone need to create at least two tables in my PMA account and relevant .php files using Brackets. 
Here is my account name and password: (fu-zeyu, 8abcth00)
