### ISSUE TITLE
Database development

### ISSUE THREAD

**Issue by fuzeyu** [fuzeyu/2020-GPW-L5K1-E#5]
Through the database we created, check the requirement list and make some improvements of our ERD.

**Comment by fuzeyu** [comment]
@buxxuan @Les1ieLee @18996073359  Please give me feedback. And You three need to discuss here and update the management interface and sales interface's ERD.

**Comment by fuzeyu** [comment]
Make sure how many tables of management interface and sales interface we need to create in PMA. Everyone need to create at least two tables in my PMA account and relevant .php files using Brackets.
Here is my account name and password: (fu-zeyu, 8abcth00)

**Comment by buxxuan** [comment]
Ok, everyone can also use this account to modify the tables in the database.But I hope you can inform me here before modification, which part has been modified, and discuss whether it is reasonable.

**Comment by fuzeyu** [comment]
> Ok, everyone can also use this account to modify the tables in the database.But I hope you can inform me here before modification, which part has been modified, and discuss whether it is reasonable.

Yes, in oider to avoid the redundancy of data and avoid the confusing of table's creating information. Everyone who create the table should upload the framework of the table to let us konw what information already include and what else should other need to add or create in an other table.

**Comment by buxxuan** [comment]
> > Ok, everyone can also use this account to modify the tables in the database.But I hope you can inform me here before modification, which part has been modified, and discuss whether it is reasonable.
> 
> Yes, in oider to avoid the redundancy of data and avoid the confusing of table's creating information. Everyone who create the table should upload the framework of the table to let us konw what information already include and what else should other need to add or create in an other table.
Ok, let's get to work
