### ISSUE TITLE
Assign tasks

### ISSUE THREAD

**Issue by fuzeyu** [fuzeyu/2020-GPW-L5K1-E#6]
After building the database, we can start to assign code tasks

**Comment by 18996073359** [comment]
In this part, I think we should make a table and assign work in the table through discussion. Next, I will show a demonstration. This is just a demonstration I wrote, and the contents can be adjusted according to our specific 
file:///C:/Users/Administrator/Desktop/work%20plan.htm

**Comment by 18996073359** [comment]
It seems that there are some problems with the transmission of the table. Do you have any good Suggestions?

**Comment by 18996073359** [comment]
[work plan.xlsx](https://github.com/fuzeyu/2020-GPW-L5K1-E/files/4534610/work.plan.xlsx)
Here is a demonstration of the work schedule.

**Comment by fuzeyu** [comment]
> work plan.xlsx
> Here is a demonstration of the work schedule.

This work plan is in detiled, but have not assigned to every member, so that we do dot know konw who did what. I will allot the tasks to everyone.

**Comment by fuzeyu** [comment]
Jerry and Albert need to create a specific ERD of management interface before May  8.  
  
Liana and Lesile need to create a detailed ERD of sales interface before May 8.

**Comment by fuzeyu** [comment]
After finish the ERD diagram, start to do the relevant part of interface's index.html. Two people as a small group and after the generally work completed, we can exchanges the project to make some improvement of our system.
