### ISSUE TITLE
prototype design

### ISSUE THREAD

**Issue by fuzeyu** [fuzeyu/2020-GPW-L5K1-E#8]
According to the template we found, please change、 update、 or delete some functions which more closely to our final project.

**Comment by fuzeyu** [comment]
Please give your feedback!

**Comment by buxxuan** [comment]
This means you can just change the code template, right? I mistakenly thought it was to draw a prototype of the system.

**Comment by fuzeyu** [comment]
> This means you can just change the code template, right? I mistakenly thought it was to draw a prototype of the system.

No, just changes the code which i alread upload to <code>. Clone them in your local files, then use brackets to editing. You can test the functions on internet with update them in Filezilla

**Comment by buxxuan** [comment]
> > This means you can just change the code template, right? I mistakenly thought it was to draw a prototype of the system.
> 
> No, just changes the code which i alread upload to code.
> Clone them in your local files, then use brackets to editing. You can test the functions on internet with update them in Filezilla
Okay, got it

**Comment by Les1ieLee** [comment]
> > > 这意味着您只需更改代码模板，对吧？我错误地认为这是绘制系统原型。
> > 
> > 
> > 不，只需更改我已经上传到代码的代码即可。
> > 将它们克隆到本地文件中，然后使用方括号进行编辑。您可以通过在Filezilla中更新它们来测试Internet上的功能，知道
> > 了



> > > This means you can just change the code template, right? I mistakenly thought it was to draw a prototype of the system.
> > 
> > 
> > No, just changes the code which i alread upload to code.
> > Clone them in your local files, then use brackets to editing. You can test the functions on internet with update them in Filezilla
> > Okay, got it

In the last discussion, we determined the template of user interface and background management interface. We need to complete the code preparation and upload it to GitHub for us to see. I think I need to learn some skills of GitHub shared code editing.
