### ISSUE TITLE
prototype development

### ISSUE THREAD

**Issue by fuzeyu** [fuzeyu/2020-GPW-L5K1-E#9]
Aftre the first phase of prototype design, discuss here to decide the final prototype template.

**Comment by fuzeyu** [comment]
After decide the prototype model, start to changes code and create and link new tables in the index and other files.

**Comment by fuzeyu** [comment]
Please give me feedback, if the template are Ok? If there are some questions, we can change another one. If no problem, we will use them to change our code. @buxxuan @Les1ieLee @18996073359

**Comment by Les1ieLee** [comment]
The prototype model is OK, and the library starts to change the code, as I've seen in the new list of indexes and other files. There are no problems now.
